version: "3"
services:
  app:
    image: metabase/metabase:latest
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - data:/metabase-data/metabase.db
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    restart: always
volumes:
  data:
    driver: local